//interface e um tipo de classe que contem especificacoes para
//outras classes...
//um manual de implementacao pra outras classes...
//dentro de uma interface e escrito uma assinatura de metodos...
public interface SerVivo18 {
    //atributo...nao podem ser private e nem protected
    //esses atributos na interface nao e possivel modificar 
    //esses valores pelas classes...
    public Boolean vivo=true;
    //assinatura dos metodos...
    public void mover();
    public void comer(int massa);
    public void info();
}
